name: WSMC
version: ${project.version}
description: WebSocket proxy to Minecraft
author: deathcap

main: deathcap.wsmc.WsmcBukkitPlugin
load: STARTUP

commands:
   web:
     description: TODO
     permission: web.command
     usage: N/A